// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB583j7MIAWBN4UKpkj0yZ6zOjz7rwiXYM',
    appId: '1:898422302240:android:f08033b7a597ceb898fe45',
    messagingSenderId: '898422302240',
    projectId: 'crypto-trader-e276d',
    storageBucket: 'crypto-trader-e276d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV4AgObNUY88MSImInVSrG_-z8WhgPmAA',
    appId: '1:898422302240:ios:d2f0fd58b28f76da98fe45',
    messagingSenderId: '898422302240',
    projectId: 'crypto-trader-e276d',
    storageBucket: 'crypto-trader-e276d.appspot.com',
    iosClientId: '898422302240-hoe1jhop5cs768a53h8bh0vicn9ivbuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoTrader',
  );
}
